# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/sprindjack/subgo/master/index3.html

- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/sprindjack/subgo/master/index3.html

- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/sprindjack/subgo/master/index3.html
     
- type: web-fanqiangdang
  options:
    url: https://raw.githubusercontent.com/sprindjack/subgo/master/index3.html
     
- type: web-freessrxyz
  options:
    url: https://raw.githubusercontent.com/sprindjack/subgo/master/index3.html
