# 订阅链接
- type: subscribe
  options:
    url: https://soacg.pp.ua/subgov2/

- type: webfuzzsub
  options:
    url: https://soacg.pp.ua/subgov2/

- type: webfuzz
  options:
    url: https://soacg.pp.ua/subgov2/

     
- type: web-fanqiangdang
  options:
    url: https://soacg.pp.ua/subgov2/

     
- type: web-freessrxyz
  options:
    url: https://soacg.pp.ua/subgov2/
